### ISSUE TITLE
Criar página de Perguntas frequentes 

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#26]
## **Objetivo**

**Como** usuário
**Quero** acessar o link do menu "Tira Dúvidas"
**Para** ver as perguntas frequentes sobre o  Elmo

## **Contexto**

Em reunião do dia 18/02/2021 com o Publicilab ficou acertado que as perguntas frequentes serão coletadas e depois repassadas para que o Designlab crie a página.
Aqui o documento que estamos utilizando para as perguntas frequentes:
https://docs.google.com/document/d/11BBPmhBmxAqVnNNL43TmQ0XDiFesVg3J2ujPr3DRWt4/edit

## **Publicilab**

- [x] Coletar perguntas mais frequentes
- [x] Verificar e corrigir perguntas

## **Designlab**
- [x] Criar página
- [x] Colocar seção perguntas frequentes da home na nova página
- [x] Atualizar perguntas
- [x] Inserir "Tira Dúvidas" link no menu

## **Critérios de Aceitação**

**Dado que** estou no site do Elmo
**Quando** acesso o link "Tira Dúvidas"
**Então** vejo as principais dúvidas frequentes sobre o Elmo

**Comment by clarissagpeixoto** [comment]
Pessoal, havíamos conversado em uma reunião passada (sugestão da @Clarisse1983 ) que teríamos dois blocos de perguntas: um bloco relacionado à compra do produto/treinamento e um bloco relacionado ao próprio treinamento. Esse último ainda está em processo de refinamento. 
Segue link de acesso à dúvidas relacionadas à compra do produto/treinamento: https://drive.google.com/file/d/1HoeE6t4BLWjTTIA0ijexXn3SBmd3nCmK/view?usp=sharing

**Comment by marameida** [comment]
**1. Aquisição do equipamento**

**Onde posso comprar o Elmo?**

Olá! Somos do Núcleo de Inovação Tecnológica da Escola de Saúde Pública do Ceará. Respondendo  à sua dúvida, seguem abaixo algumas informações.

💰 Para a aquisição do Elmo, solicitamos que você entre em contato com a Esmaltec através dos telefones: (85) 98802.6585 / (85) 3299.8716

📚 Posteriormente, para capacitação dos profissionais que irão manipular o dispositivo:

👩‍🔬 👨‍🔬Caso os profissionais sejam da rede pública do Ceará, você deve fazer um agendamento via Whats App com a Dr. Cléo (85 9193-3828) ou com o Rafael (85 8702-0755). 

🚑🏥 Caso a demanda seja de profissionais que atuam na rede privada, você deve fazer a solicitação de uma proposta comercial através do e-mail: comercial@esp.ce.gov.br, incluindo o a quantidade de pessoas que precisam ser treinadas e a instituição a qual pertence.

🏬 Ambos os treinamentos ocorrem de forma presencial, na Escola de Saúde Pública do Ceará, por enquanto. 

🗺️ Em breve,  teremos uma plataforma de ensino à distância para atender equipes de todo o Brasil.

☎️ Dúvidas: (85) 9 8439.0220

**Como solicitar o Elmo para a rede pública?**

Caso você seja de uma instituição de** saúde pública do Ceará**, você deve enviar um ofício para o e-mail assessoriaseade@gmail.com, incluindo uma justificativa para aquisição do equipamento, e aguardar resposta.
O equipamentos serão enviados de acordo com a disponibilidade do produto.
Em caso de dúvida, ligue: 3101-2624 (Ana Paula).

**2. Treinamento**

**Quero fazer o treinamento. O que devo fazer?**

Olá! Somos no Núcleo de Inovação Tecnológica da Escola de Saúde Pública do Ceará. Segue resposta a sua pergunta:
 
👩‍🔬 👨‍🔬Caso os profissionais sejam da rede pública do Ceará, você deve fazer um agendamento via Whats App com a Dr. Cléo (85 9193-3828) ou com o Rafael (85 8702-0755). 

🚑🏥 Caso a demanda seja de profissionais que atuam na rede privada, você deve fazer a solicitação de uma proposta comercial através do e-mail: comercial@esp.ce.gov.br, incluindo o a quantidade de pessoas que precisam ser treinadas e a instituição a qual pertence.

🏬 Ambos os treinamentos ocorrem de forma presencial, na Escola de Saúde Pública do Ceará, por enquanto. 

**Pessoas de outros estados podem fazer o treinamento?**

Queremos dar suporte a profissionais de todo o país. Estamos trabalhando muito para que isso aconteça. Em breve, teremos nossa plataforma de treinamento à distância. Por enquanto, nossos treinamentos estão acontecendo apenas presencialmente na Escola de Saúde Pública do Ceará. 

👩‍🔬 👨‍🔬Caso os profissionais sejam da rede pública do Ceará, você deve fazer um agendamento via Whats App com a Dr. Cléo (85 9193-3828) ou com o Rafael (85 8702-0755). 

🚑🏥 Caso a demanda seja de profissionais que atuam na rede privada, você deve fazer a solicitação de uma proposta comercial através do e-mail: comercial@esp.ce.gov.br, incluindo o a quantidade de pessoas que precisam ser treinadas e a instituição a qual pertence.

**Quero treinar minha equipe, mas somos de outro estado. Pode?**

Pode sim. Entre em contato conosco que pensaremos em uma proposta que se ajuste à sua demanda: comercial@esp.ce.gov.br.

**Quanto tempo dura o treinamento?**
Capacitações à distância têm duração de seis horas.
Capacitações presenciais têm duração de quatro horas.

**Existe uma quantidade mínima de alunos para fechar turma de outros estados?**

Sim, existe. As turmas são limitadas por conta do método utilizado, a simulação realística. A quantidade de alunos deve ser no máximo 10.

**A ESP/CE emite certificação para quem concluiu o curso?**
Por enquanto, não. Emitimos apenas um certificado de participação. 

**É obrigatório o treinamento?**
Não. Uma vez aprovado pela Anvisa, qualquer profissional de saúde está respaldado a usar o equipamento. Porém, tratando-se de um dispositivo novo de suporte respiratório, recomenda-se fortemente o treinamento dos profissionais que irão manuseá-lo, para maior segurança.

**Quem são os professores?**
São três profissionais: um médico (a), um enfermeiro (a) e um(a) fisioterapeuta. Todos envolvidos no projeto e qualificados pela ESP/CE.

**Posso atuar como multiplicador do conhecimento para minha equipe?**
Sim, pode. Quem faz o curso está apto a replicar o conhecimento para outros profissionais, utilizando uma estrutura mínima necessária para que esse conhecimento seja repassado de maneira efetiva.

**Existe algum hotsite informativo do produto com valores de aquisição?**
Sim: https://sus.ce.gov.br/elmo/
No menu, você deve acessar o botão **Como adquirir**. Lá, você encontrará o contato da Esmaltec, única empresa do Brasil a produzir o dispositivo.

**3. Parcerias**

**Sou investidor e quero contribuir para a produção de mais Elmos. Como posso contribuir?**
Entre em contato conosco através do telefone/Whast App: 85 9 8439.0220 que pensaremos em soluções juntos.

**Quero doar e contribuir para a produção de mais Elmos. Como posso realizar minha doação?**
Você deve realizar a compra normalmente através da Esmaltec (https://sus.ce.gov.br/elmo/#vendas) e entrar em contato com a Escola de Saúde Pública do Ceará para falarmos sobre o treinamento para o uso do dispositivo: 85 9 8439.0220. 


**Fiz o curso e estou com dúvidas, quem devo procurar?**
**Qual é a metodologia utilizada?**


**QUADRO COM DÚVIDAS SOBRE A MANIPULAÇÃO DO APARELHO**

**Comment by marameida** [comment]
Dados à serem discutidos com @danielgula  em reunião 27/05/2021

**Comment by marameida** [comment]
Repasse feito em reunião com @clarissagpeixoto e @danielgula. Dúvidas serão revisadas para efetivação da demanda.

**Comment by clarissagpeixoto** [comment]
Daniel, precisamos aprimorar o FAQ do site do Elmo. 
Solicitamos que seja incluso no menu, se possível, o item "Dúvida Frequentes" e os submenus "Aquisição e treinamento"/"Dúvidas Técnicas".

As dúvidas técnicas sobre o manejo serão aprimoradas pelos CEDES. Por enquanto, podemos permanecer com as quatro que estão no site.

As dúvidas sobre os treinamentos seguem no link a seguir: https://docs.google.com/document/d/1XDlckE6xvLj7qpTqUJerO574DEVHPVuYwuZ-rij_CxU/edit

**Comment by danielgula** [comment]
> Daniel, precisamos aprimorar o FAQ do site do Elmo.
> Solicitamos que seja incluso no menu, se possível, o item "Dúvida Frequentes" e os submenus "Aquisição e treinamento"/"Dúvidas Técnicas".
> 
> As dúvidas técnicas sobre o manejo serão aprimoradas pelos CEDES. Por enquanto, podemos permanecer com as quatro que estão no site.
> 
> As dúvidas sobre os treinamentos seguem no link a seguir: https://docs.google.com/document/d/1XDlckE6xvLj7qpTqUJerO574DEVHPVuYwuZ-rij_CxU/edit

Fiz alguns comentários no doc referentes aos temas e perguntas formuladas para melhor compreensão dos usuários. A página com a versão atual (ainda bloqueada para o consumidor) é essa:
https://sus.ce.gov.br/elmo/perguntas-frequentes/
A senha para acesso foi enviada no grupo do Telegram.

**Comment by clarissagpeixoto** [comment]
@danielgula respondi a todos os seus questionamentos agora. Dá uma olhada.

**Comment by marameida** [comment]
No aguardo por validação do Uirá para publicação no site.

**Comment by marameida** [comment]
Enviado email para CEDES e ASCOM para validação.
 
1. Recebido até o momento devoltiva do CEDES (Rafael)(https://drive.google.com/drive/u/1/folders/1B1WY7lenMhe3DF7Xr72t4_0h0kKzpSz9).
2. Ariane da ASCON referiu estar trabalhando no retorno, juntamente com a Betina indicada pelo Dr Marcelo.
OBS: Após devolutivas, as sugestões serão acatadas e publicadas no site do Elmo.

**Comment by clarissagpeixoto** [comment]
Vou checar os ajustes passados pela ASCOM e pelo CEDES e dar continuidade ao trabalho.

**Comment by clarissagpeixoto** [comment]
@marameida vi que algumas pessoas desconhecem o termo FAQ (frequent answers and questions), o que gerou vários ruídos de comunicação. Dessa forma, sugiro a mudança para o termo "Perguntas Frequentes". No tocante à aprovação, o CEDES não havia entendido direito a demanda. Repassei pessoalmente para o Rafa, que ficou de analisar e me dar um retorno. Mostrei a ele a lista de dúvidas técnicas que venho recebendo, mas pelo que coversamos, acredito que elas não devam entrar nessa lista, visto que são questões delicadíssimas que envolvem a esterilização.

**Comment by clarissagpeixoto** [comment]
Desconsiderar o arquivo que o Rafa enviou anteriormente.

**Comment by marameida** [comment]
No aguardo por devoltiva do CEDES para finalização do arquivo. Repassado para Designlab.

**Comment by clarissagpeixoto** [comment]
@danielgula o Rafa nos passou alguns ajustes de texto. É só copiar e colar, substituindo os textos que estão nas respectivas sessões atualmente.

**Que tipos de paciente podem se beneficiar?**
O dispositivo tem indicação para o quadro clínico de insuficiência respiratória hipoxêmica de leve a moderada e também pode auxiliar casos em início de gravidade.
Apesar de surgir como alternativa mais barata e rápida no tratamento de pacientes com SARS-CoV-2, o equipamento pode ser útil, também, no tratamento de outras enfermidades que causem insuficiências respiratórias hipoxêmicas.

**Existe a modalidade de educação à distância EAD?**
Sim, existe. O treinamento virtual é feito com a nossa equipe de instrutores em sincronismo com a turma de participantes em tempo real. Essa modalidade é voltada, principalmente, para atender profissionais de saúde de outros estados.

**Qual é a metodologia?**
A metodologia é a simulação realística baseada em competência. O objetivo é desenvolver um conjunto de habilidades cognitivas, psicomotoras e perceptuais, para o desenvolvimento de uma competência única “Capacidade para Manejo do Elmo em Pacientes com Insuficiência Respiratória Aguda Hipoxêmica”

**Existe uma quantidade mínima de alunos para fechar turma de outros estados?**
• Quantidade mínima: 6 alunos
• Quantidade máxima: 10 alunos

**A ESP/CE emite certificação para quem concluiu o curso?**
Não. Emitimos uma declaração de participação, pois se trata de um treinamento de curta duração (quatro horas).

**Quem são os facilitadores/instrutores?**
São três profissionais: um médico (a), um enfermeiro (a) e/ou um(a) fisioterapeuta. Todos envolvidos no projeto de treinamento de habilidades sobre o manejo do Elmo, qualificados pela equipe de desenvolvedores e pesquisadores do ElmoCpap 1.0, e desenvolvidos sistematicamente pela equipe de desenvolvimento educacional da ESP/CE para melhor aplicabilidade da metodologia da simulação realística baseada em competência e treinamento de habilidades.

**Fiz o treinamento e estou com dúvidas: a quem devo procurar?**
Você deve procurar o “ponto focal” da sua turma, profissional da saúde que está em contato conosco através do grupo de Whats App específico para sanar dúvidas, discutir casos clínicos, compartilhar experiências e demais aspectos da aplicabilidade técnica e clínica do ElmoCpap 1.0 que favorecem a curva de aprendizagem dos profissionais treinados pela ESP/CE.

**Comment by clarissagpeixoto** [comment]
@danielgula EXCLUIR essa parte
Sou investidor e quero contribuir para a produção de mais Elmos. Como posso contribuir?
Entre em contato conosco através do telefone/Whatapp: (85) 98439.0220 que pensaremos em soluções juntos.

**Comment by danielgula** [comment]
Página criada e disponibilizada no site.

https://sus.ce.gov.br/elmo/perguntas-frequentes/

**Comment by clarissagpeixoto** [comment]
@marameida 
- A seção "PARCERIAS - Sou investidor e quero contribuir para a produção de mais Elmos. Como posso contribuir?" precisa ser excluída, como solicitado acima. O texto foi apenas alterado e está com informações inconsistentes.
- A seção deve ser chamada "Perguntas Frequentes", como consta na descrição da atividade, não "Tira-dúvidas".
- Fora isso, reli as perguntas antigas (que já estavam no site desde o início) e percebi alguns erros, como o fato de que o Elmo "pode ser produzido em escala industrial".

**Comment by marameida** [comment]
Acordado com @danielgula ajustes nas demandas. Serão refinadas com @clarissagpeixoto.
