### ISSUE TITLE
Upgrade da landing page do sus.ce.gov.br

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#64]
## **Objetivo**

**Como** usuário
**Quero** acessar a página principal do sus.ce.gov.br
**Para** ver os produtos e serviços do FeliciLab

## **Contexto**

A página inicial do sus.ce.gov.br está com os dizeres "em breve" e temos muitos produtos publicados em plataformas digitais. Queremos melhorar essa página para dar mais visibilidade e conexões aos projetos e à marca FeliciLab.

### **Publicilab**
- [x] Criar uma narrativa para a landing page
- [ ] Escrever texto publicitário

### **Designlab**
- [x] Listar novos produtos e serviços a serem incluídos
- [x] Recriar a página no formato do Divi
- [x] Incluir emergencialmente novos produtos na página atual
- [ ] Definir assinatura visual e tons cromáticos
- [ ] Criar layout para a página (padrão da nova marca)
- [ ] Implementar no Divi
- [ ] Publicar e fazer testes mobile

## **Critérios de Aceitação**

**Dado que** estou na Internet
**Quando** acesso o site sus.ce.gov.br
**então** vejo a landing page da educação permanente em saúde

**Comment by RaniGub** [comment]
Considerar refinamento com a @Clarisse1983 e @pauloamoreira
