### ISSUE TITLE
Criar MVP1 do Site Cisec

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#65]
## **Objetivo**

**Como** designer
**Quero** criar o site do Sisec
**Para** publicar na internet o MVP1

## **Contexto**

A equipe do Centro de Inteligência pretende lançar uma versão inicial do site do Cisec, com algumas funcionalidades e conteúdos para seu público-alvo, gestores, universidades e tomadores de opinião. Esse site já foi criado dentro da plataforma multisite do Wordpress, no endereço https://sus.ce.gov.br/cisec/
O site precisa de um layout, que foi feito pela equipe do projeto de forma preliminar. A tarefa demanda conversas com Marcos, Valéria e Rano para refinar as páginas a serem criadas e os links para os serviços e site administrativo da plataforma.

## **Escopo**

- [x] desenho da arquitetura básica (Marcos)
- [x] Ajustes na experiência do usuário (Valéria)
- [x] Template no Divi
- [x] Criação de menu
- [x] Criação do rodapé
- [ ] Criação de páginas
- [ ] Integração com simuladores
- [ ] Links para instâncias externas
- [ ] Criação de usuários editores
- [ ] Treinamento no Wordpress

## **Critérios de Aceitação**

**Dado que** sou pessoa usuária
**Quando** preciso ver dados sobre inteligência em saúde
**então** acesso i site https://sus.ce.gov.br/cisec/ com o MVP1

## Observações
Serão fornecidos os links para todos os projetos e protótipos. Negociar com Valéria e Matheus um visual com experiência do usuário adequada.

**Comment by RaniGub** [comment]
Comentário copiado da tarefa EscolaDeSaudePublica/DesignLab#97, está mais adequado a este card.

Segue relatório do refinamento da tarefa com a equipe.

**Marca**
Sobre ela, precisamos fazer alguns ajustes visuais para melhor uso nas plataformas pretendidas.

Soluções
O Cisec está desenvolvendo diversas soluções que serão acessadas em formato web e mobile. A equipe composta por colegas do NIT + Cisec já possuem protótipos funcionais. Eles precisarão de um site e um ambiente mobile para rodar.
Link para o protótipo: https://www.figma.com/file/AF7SfWrTIvXlmGeEdUE3JG/Simulador?node-id=103%3A740

**Site**
De acordo com refinamento da equipe, a estrutura do Menu do site será a seguinte:

Home - vai ser a própria logo
-- Institucional
-- Soluções
-- Como Usar
-- Simulador
-- Variantes
-- Derivadas
-- Vacinas
Perguntas Frequentes
Contato
Área do gestor
Sobre os banners

Banner central - chamadas para notícias (Sesa, ESP)
iSUS - publicidade de produtos
Link de acesso ao protótipo: https://www.figma.com/proto/a67eihcskHYp7HttQIg0GM/Dashboard?node-id=211%3A69&scaling=min-zoom&page-id=3%3A2

**Papéis**
Quem vai atualizar as páginas estáticas - usuário no WP do Cisec
Quem vai montar o site - Felicilab
Quem vai integrar as soluções - Cisec + NIT
Quem vai refinar a Assinatura - Felicilab

**Encaminhamentos**
Nesta etapa, solicitamos um stakeholder apresentar o projeto visual para a ASCOM, de maneira que possa criar um manual de identidade para toda a plataforma. Dessa forma iniciaremos a execução da demanda de criação do site.
