### ISSUE TITLE
EAP#525 Site Programa Cuidar Melhor

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#85]
## EAP

[Concurso Município Inovador - Programa Cuidar Melhor\Produção e customização do site](https://projetos.esp.ce.gov.br/issues/525)

Escopo

- [x] Criar arquitetura
- [x] Alterar pdfs para páginas
- [x] transferir página o Programa
- [x] transferir indicadores
- [x] Criar página do prêmio

**Comment by danielgula** [comment]
Site foi publicado e está funcional. Fica pendente a manutenção do redirecionamento, que será resolvido depois de reunião com a infra dia 24/11
