### ISSUE TITLE
MVP 1 - Site da Residência

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/sus.ce.gov.br#90]
## **Objetivo**

**Como** Residentes e possíveis ingressantes a residentes
**Quero** precisam obter informações, ter interação e comunicação  
**Para** se relacionar com o programa da residência.

## **Contexto**

Os residentes precisam de um site para melhorar o relacionamento com os programas de Residência e este, por sua vez, requer uma melhor visibilidade do seu conteúdo informativo. Os possíveis ingressantes precisam obter informações a cerca do programa, dos editais, bem como indicativos e outros assuntos que possa interessar a sua participação. Neste sentido, devemos criar um site que possa habilitar essa interação do residente e possíveis ingressantes para com o programa servindo como canal informativo e de comunicação.

## **Escopo**

- [x] Arquitetura da Informação
- [x] Protótipo Funcional
- [x] Esboço do Site
- [x] Refinamento
- [x] Inception
- [x] Jornada
- [x] Conteúdo
- [ ] Contextualização do novo responsável 
- [ ] Reunião com Dipsa para apresentação do site no Wordpress
- [ ] Cadastrar administradores/editores 

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
@elpadrejorge esse Épico conecta as tarefas criadas até agora para o Site da Residência. Acho interessante uma nova tarefa, relacionada à revisão das informações, ser criada para refinarmos o escopo dela. Nesse Épico #90 você conseguirá ver todas as tarefas relacionadas até então com comentários, daí você consegue um complemento do contexto que lhe passei hoje.
