### ISSUE TITLE
Site Felicilab 2.0

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#94]
## **Objetivo**

**Como** usuário
**Quero** acessar o novo site do Felicilab
**Para** ver pessoas, projetos e serviços

## **Contexto**

- O site do Felicilab teve um estudo elaborado pelo @wforte88 que envolve uma arquitetura baseada em projetos, categorias de projetos e templates exclusivos para dar dinâmica aos conteúdos do site, apresentando o time, projetos, produtos, metodologias e resultados. O site atual precisa se adequar a essa nova arquitetura, e aos poucos será remodelado com novo visual.

## **Escopo**

- [x] Reestruturar categorias do site e arquitetura
- [x] Revisão da AI
- [x] Organizar posts e projetos atualmente publicados
- [x] Exportar e importar templates novos
- [x] Construir novas páginas
- [x] Publicar projetos de pessoas
- [x] Publicar projetos de produtos
- [x] Publicar projetos de labs
- [x] Verificar experiência mobile

## **Critérios de Aceitação**

**Dado que** estou na Internet
**Quando** entro no site Felicilab
**então** vejo a experiência 2.0 do Felicilab

**Comment by danielgula** [comment]
Com todas as atividades feitas para esta nova versão, este épico pode ser encerrado. Aguardaremos os próximos passos definindo  a inception para o desenho de uma nova versão.
